<a href="https://colab.research.google.com/github/armandoordonez/stats_learning_book/blob/main/Ex_2_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

# based in https://botlnec.github.io/islp/sols/chapter2/exercise7/

data = {'X1': pd.Series([0,2,0,0,-1,1]), 'X2': pd.Series([3,0,1,1,0,1]), 'X3': pd.Series([0,0,3,2,1,1]), 'Y': pd.Series(['Red','Red','Red','Green','Green','Red'])}
df = pd.DataFrame(data)
df.index = np.arange(1, len(df) + 1)
df

#https://raw.githubusercontent.com/armandoordonez/stats_learning_book/main/College.csv

   X1  X2  X3      Y
1   0   3   0    Red
2   2   0   0    Red
3   0   1   3    Red
4   0   1   2  Green
5  -1   0   1  Green
6   1   1   1    Red

In [2]:
from math import sqrt
df['distance']=np.sqrt(df['X1']**2+df['X2']**2+df['X3']**2)
df

   X1  X2  X3      Y  distance
1   0   3   0    Red  3.000000
2   2   0   0    Red  2.000000
3   0   1   3    Red  3.162278
4   0   1   2  Green  2.236068
5  -1   0   1  Green  1.414214
6   1   1   1    Red  1.732051

In [3]:
df.sort_values(['distance'])

   X1  X2  X3      Y  distance
5  -1   0   1  Green  1.414214
6   1   1   1    Red  1.732051
2   2   0   0    Red  2.000000
4   0   1   2  Green  2.236068
1   0   3   0    Red  3.000000
3   0   1   3    Red  3.162278